version: "2"

services:
  mqtt_trigger:
    build: .
    # with the following line, an alternativ python app could be started
    # command: python3 sonosServer.py
    volumes:
      - ./code:/code
    restart: always
#    network_mode: "host"
    container_name: "mqtt_trigger"
